apiVersion: v1
kind: Secret
metadata:
  name: keydb-tls-certs
  namespace: default
type: kubernetes.io/tls
data:
  # These are example base64-encoded certificates
  # In production, use proper certificates from a CA
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCi4uLgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCi4uLgotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0t
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCi4uLgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t
  dh.pem: LS0tLS1CRUdJTiBESCBQQVJBTUVURVJTLS0tLS0KLi4uCi0tLS0tRU5EIERIIFBBUkFNRVRFUlMtLS0tLQ==
