name: Release

on:
  push:
    tags:
      - 'v*'

env:
  REGISTRY: docker.io
  IMAGE_NAME: opendi/keydb-operator

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.19'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Get version from tag
      id: version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.version.outputs.VERSION }}
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
        labels: |
          org.opencontainers.image.title=KeyDB Operator
          org.opencontainers.image.description=A modern Kubernetes operator for KeyDB
          org.opencontainers.image.version=${{ steps.version.outputs.VERSION }}
          org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
          org.opencontainers.image.revision=${{ github.sha }}
          org.opencontainers.image.created=${{ github.event.head_commit.timestamp }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Generate changelog
      id: changelog
      run: |
        if [ -f CHANGELOG.md ]; then
          # Extract changelog for this version
          awk '/^## \['"${GITHUB_REF#refs/tags/}"'\]/{flag=1; next} /^## \[/{flag=0} flag' CHANGELOG.md > release_notes.md
        else
          echo "Release ${{ steps.version.outputs.VERSION }}" > release_notes.md
          echo "" >> release_notes.md
          echo "### Changes" >> release_notes.md
          git log --pretty=format:"- %s" $(git describe --tags --abbrev=0 HEAD^)..HEAD >> release_notes.md
        fi

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        body_path: release_notes.md
        draft: false
        prerelease: ${{ contains(steps.version.outputs.VERSION, '-') }}
        files: |
          config/crd/bases/*.yaml
          config/samples/*.yaml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Update deployment manifests
      run: |
        # Create deployment bundle directory
        mkdir -p deploy

        # Generate basic deployment manifest with the new image
        cat > deploy/keydb-operator.yaml << EOF
        # This deployment manifest is auto-generated during release
        # For the latest version, see: https://github.com/opendi/keydb-operator/releases
        apiVersion: v1
        kind: Namespace
        metadata:
          name: keydb-operator-system
        ---
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: keydb-operator-controller
          namespace: keydb-operator-system
          labels:
            app: keydb-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: keydb-operator
          template:
            metadata:
              labels:
                app: keydb-operator
            spec:
              containers:
              - name: manager
                image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.version.outputs.VERSION }}
                ports:
                - containerPort: 8080
                  name: metrics
                - containerPort: 9443
                  name: webhook
                resources:
                  requests:
                    cpu: 100m
                    memory: 128Mi
                  limits:
                    cpu: 500m
                    memory: 512Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  runAsNonRoot: true
              serviceAccountName: keydb-operator-controller
        EOF

        # Commit updated manifests
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add deploy/
        git commit -m "Update deployment manifests for ${{ steps.version.outputs.VERSION }}" || exit 0
        git push origin HEAD:main
